# ----------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# ----------------------------------------------------------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ob-pattern-1.resource.prefix" . }}-obiam-resources-security
  namespace : {{ .Release.Namespace }}
binaryData:
  client-truststore.jks: |-
    {{ .Files.Get "resources/obiam/client-truststore.jks" | b64enc }}
  wso2carbon.jks: |-
    {{ .Files.Get "resources/obiam/wso2carbon.jks" | b64enc }}
   