dependencies:
  - name: mysql-ob
    version: "3.0.0-1"
    repository: "file://../database/mysql-ob"
    condition: wso2.deployment.dependencies.mysql
  - name: nfs-server-provisioner
    version: "1.1.0"
    repository: "https://helm.wso2.com"
    condition: wso2.deployment.dependencies.nfsServerProvisioner
